#!/bin/bash

set -e 

USERID=$(id -u)
R="\e[31m"
G="\e[32m"
N="\e[0m"

echo -e " $G Green $R Red $N "

echo "User Id :$USERID "

if [ $USERID -ne 0 ] 
then 
    echo -e "$R Please run this programme with root access $N"
    exit 1
else
    echo -e "$G This user is a super user $N"
fi 


dnf install myyysqll -y 

dnf install gitt -y