- name: conditions
  hosts: localhosts
  become: yes
  tasks:
  - name: conditions
    ansible.builtin.debug: id expense
   
  - name: say Hi
    ansible.builtin.debug:
      msg: "Hi am I getting executed"