- name: Devlaring Variables in play level
  hosts: localhosts
  vars:
    course: "DevOps with AWS"
    trainer: "siva kumar"
  tasks:
  - name: variables calling
    ansible.builtin.debug:
      msg: "I am learning {{course}} from the trainer {{trainer}}"