- name: conditions
  hosts: localhosts
  become: yes
  tasks:
  - name: conditions
    ansible.builtin.command: id expense
    register: USER
    ignore_errors: true

  - name: printing register variable
    ansible.builtin.debug:
      msg: "printing data: {{USER}}"
