- name: conditions
  hosts: localhosts
  become: yes
  tasks:
  - name: conditions
    ansible.builtin.command: id expense
    ignore_errors: true
   
  - name: say Hi
    ansible.builtin.debug:
      msg: "Hi am I getting executed"