- name: Filters
  hosts: localhosts
  tasks:
  - name: default value
    ansible.builtin.debug:
      msg: " Hello {{Course | default('Ansible') }}"

- name: upper case
  hosts: localhosts
  vars:
    Greetings: "Good Morning"
  tasks:
  - name: uppercase
    ansible.builtin.debug:
      msg: " before applying filter - {{Greetings}}, In upper case: {{Greetings | upper}}"

- name: lower case
  hosts: localhosts
  vars:
    Greetings: "Good Morning"
  tasks:
  - name: convert to lowercase
    ansible.builtin.debug:
      msg: "before applying filter - {{Greetings}}, In lower case:  {{Greetings | lower}}"