- name: Devlaring Variables in play level
  hosts: localhosts
  vars_files:
  - varfile.yaml
  tasks:
  - name: variables calling
    ansible.builtin.debug:
      msg: "I am learning {{course}} from the trainer {{trainer}}"