- name: Filters
  hosts: localhosts
  tasks:
  - name: default value
    ansible.builtin.debug:
      msg: " Hello {{Course | default('Ansible') }}"

- name: upper case
  hosts: localhosts
  vars:
    Greetings: "Good Morning"
  tasks:
  - name: uppercase
    ansible.builtin.debug:
      msg: " before applying filter - {{Greetings}}, In upper case: {{Greetings | upper}}"

- name: lower case
  hosts: localhosts
  vars:
    Greetings: "Good Morning"
  tasks:
  - name: convert to lowercase
    ansible.builtin.debug:
      msg: "before applying filter - {{Greetings}}, In lower case:  {{Greetings | lower}}"

- name: Unique
  hosts: localhosts
  vars:
    num: [1,2,3,2,4,3,5,9,1,2,3,4,5]
  tasks:
  - name: eliminating same numbers
    ansible.builtin.debug:
      msg: "unique   {{num | unique}}"

- name: Min and max values
  hosts: localhosts
  vars:
    ages: [18,21,32,22,41,32,52,92,19,23,36,47,59]
  tasks:
  - name: min
    ansible.builtin.debug:
      msg: " Minimum age to vote:  {{ages | min}}"
  - name: max
    ansible.builtin.debug:
      msg: " oldest person by age :  {{ages | max}}"

- name: Coverting dictionary to list items
  hosts: localhosts
  vars:
    my_dict:
      trainer: sivakumar
      course: Devops
      Duration: 4-months
  tasks:
  - name: before converting 
    ansible.builtin.debug:
      msg: "Before converting {{ my_dict }}"
  - name: after converting 
    ansible.builtin.debug:
      msg: "after converting {{ my_dict | dict2items }}"

- name: Coverting list items to dictionary 
  hosts: localhosts
  vars:
    my_list:
      - {'key': 'trainer', 'value': 'sivakumar'} 
      - {'key': 'course', 'value': 'Devops'} 
      - {'key': 'Duration', 'value': '4-months'}
      
  tasks:
  - name: before converting 
    ansible.builtin.debug:
      msg: "Before converting {{ my_list }}"
  - name: after converting 
    ansible.builtin.debug:
      msg: "after converting {{ my_list | items2dict }}"



