- name: Filters
  hosts: localhosts
  tasks:
  - name: default value
    ansible.builtin.debug:
      msg: " Hello {{Course | default('Ansible') }}"

- name: upper case
  hosts: localhosts
  vars:
    Greetings: "Good Morning"
  tasks:
  - name: uppercase
    ansible.builtin.debug:
      msg: " {{Greetings | upper}}"